DailyFresh/DailyFresh/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('search/', include('haystack.urls')),  # 全文检索框架
    url(r'^apps/', include(('apps.urls', 'apps'), namespace='apps')),
    url(r'^user/', include(('apps.user.urls', 'user'), namespace='user')),
    url(r'^cart/', include(('apps.cart.urls', 'cart'), namespace='cart')),
    url(r'^order/', include(('apps.order.urls', 'order'), namespace='order')),
    url(r'', include(('apps.goods.urls', 'goods'), namespace='goods')),
]

DailyFresh/apps/cart/urls.py
from django.conf.urls import url

from DailyFresh.apps.cart.views import CartInfoView, CartAddView, CartUpdateView, CartDeleteView

urlpatterns = [
    url(r'^$', CartInfoView.as_view(), name='display'),
    url(r'^add/$', CartAddView.as_view(), name='add'),
    url(r'^update/$', CartUpdateView.as_view(), name='update'),
    url(r'^delete/$', CartDeleteView.as_view(), name='delete'),
]

DailyFresh/apps/goods/urls.py
from django.conf.urls import url

from DailyFresh.apps.goods.views import IndexView, DetailView, ListView

urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<sku_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页

]

DailyFresh/apps/order/urls.py
from django.conf.urls import url

from DailyFresh.apps.order.views import OrderPlaceView, OrderCommitView, OrderPayView, OrderCheckView, OrderCommentView

urlpatterns = [
    url(r'^place/$', OrderPlaceView.as_view(), name='place'), #提交订单页面
    url(r'^commit/$', OrderCommitView.as_view(), name='commit'), #创建订单
    url(r'^pay/$', OrderPayView.as_view(), name='pay'), #订单支付
    url(r'^check/$', OrderCheckView.as_view(), name='check'), #订单签收
    url(r'^comment/$', OrderCommentView.as_view(), name='comment'), #订单评论
]

DailyFresh/apps/user/urls.py
from django.conf.urls import url

# urlpatterns = [
#     url(r'^register/', views.register, name='register'),
#     url(r'^login/', views.login, name='login'),
#     url(r'^forget/', views.forget_password, name='forget_password'),
#     url(r'^reset/', views.reset_password, name='reset_password'),
# ]

from DailyFresh.apps.user.views import UserInfoView, RegisterView, ActiveView, LoginView, LogoutView, UserOrderView, \
    AddressView

urlpatterns = [
    # 用户中心
    url(r'^$', UserInfoView.as_view(), name='user'),

    url(r'^register/$', RegisterView.as_view(), name='register'),
    # 激活
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    url(r'^order/(?P<page>(\d)*)$', UserOrderView.as_view(), name='order'),
    url(r'^address/$', AddressView.as_view(), name='address'),

]

DailyFresh/apps/cart/models.py
from DailyFresh.db.base_model import BaseModel


class Cart(BaseModel):
    """购物车模型类"""

    class Meta:
        db_table = 'db_cart'
        verbose_name = '购物车'
        verbose_name_plural = '购物车列表'

DailyFresh/apps/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic.base import View
from django_redis import get_redis_connection

from DailyFresh.apps.goods.models import GoodsSKU


# get /cart/
class CartInfoView(View):
    """购物车页面显示"""

    def get(self, request):
        """页面展示"""
        user = request.user

        # 从redis中获取用户的购物车记录信息
        conn = get_redis_connection('default')
        # 拼接key
        cart_key = 'cart_%d' % user.id
        # hgetall()返回一个字典,字典键是商品id,值是添加的数目
        cart_dict = conn.hgetall(cart_key)

        total_count = 0
        total_amount = 0
        skus = []
        for sku_id, count in cart_dict.items():
            sku = GoodsSKU.objects.get(id=sku_id)
            amount = sku.price * int(count)
            sku.count = count
            sku.amount = amount
            skus.append(sku)

            total_count += int(count)
            total_amount += amount

        context = {
            'total_count': total_count,
            'total_amount': total_amount,
            'skus': skus,
        }
        return render(request, 'cart.html', context)


# 前端传递的参数: 商品id(sku_id) 商品数量(count)
# /cart/add
class CartAddView(View):
    """添加购物车记录"""

    def post(self, request):
        user = request.user
        # 判断用户登录情况
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'error_msg': '请登录'})

        sku_id = request.POST.get('sku_id', '')
        count = request.POST.get('count', '')
        # 校验参数
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'error_msg': '参数不完整'})

        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error_msg': '商品信息错误'})

        # 检验商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'error_msg': '商品数量必须为数字'})

        # 义务处理:添加购物车记录
        # 获取redis连接
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # hget(key, field)
        cart_count = conn.hget(cart_key, sku_id)

        # 如果用户购物车中已经添加过sku_id商品,购物车中对应商品的数目需要进行累加
        if cart_count:
            count += int(cart_count)

        # 校验商品库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'error_msg': '商品库存不足'})

        # 设置用户购车中sku_id商品的数量
        # hset(key, field, value) 存在就修改,不存在就新增
        conn.hset(cart_key, sku_id, count)

        # 获取用户购物车中商品的条目数
        cart_count = conn.hlen(cart_key)
        return JsonResponse({'res': 5, 'cart_count': cart_count, 'error_msg': '添加购物车记录成功'})


class CartUpdateView(View):
    """更新购物车记录"""

    def post(self, request):
        user = request.user
        # 判断用户是否登录
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'error_msg': '请登录'})

        # 获取参数
        sku_id = request.POST.get('sku_id', '')
        count = request.POST.get('count', '')

        # 校验参数
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'error_msg': '参数不完整'})

        # 校验商品id
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error_msg': '商品信息错误'})

        # 校验商品数量count
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 3, 'error_msg': '商品数量必须为有效数字'})

        # 连接redis
        conn = get_redis_connection('default')
        # 拼接key
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存量
        if count > sku.stock:
            return JsonResponse({'res': 4, 'error_msg': '商品库存不足'})

        # 更新用户购物车中商品数量
        conn.hset(cart_key, sku_id, count)
        return JsonResponse({'res': 5, 'error_msg': '更新购物车记录成功'})


# 前端传递的数据:商品id(sku_id)
# /cart/delete
class CartDeleteView(View):
    """购物车记录删除"""

    def post(self, request):
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'error_msg': '请登录'})

        sku_id = request.POST.get('sku_id', '')
        if not all([sku_id]):
            return JsonResponse({'res': 1, 'error_msg': '参数不完整'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'error_msg': '商品信息错误'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除记录
        # hdel(key, field)
        conn.hdel(cart_key, sku_id)

        return JsonResponse({'res': 3, 'error_msg': '删除购物车记录成功'})

DailyFresh/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static from staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {#  网页标题块  #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
                <div class="login_info fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>

			</div>
		</div>
	</div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="button" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

DailyFresh/templates/base_detail.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{% block body %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					<li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
    {# 详情页 列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

DailyFresh/templates/base_user_center.html
{# 用户中心-3页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
        {# 用户中心右侧内容块 #}
		{% block right_content %}{% endblock right_content %}
	</div>
{% endblock body %}

DailyFresh/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜-商品详情{% endblock title %}
{% block main_content %}

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' sku.category.id 1 %}">{{ sku.category.name }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.name }}</h3>
			<p>{{ sku.desc }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
				<span class="show_unit">单  位：{{ sku.unite }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>	
				</div> 
			</div>
            <div>
                <div>其他规格:</div>
                <div>
                    {% for sku in same_spu_skus %}
                        <a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a>
                    {% endfor %}
                </div>
            </div>
			<div class="total">总价：<em>{{ sku.price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
                {% csrf_token %}
				<a href="javascript:;" class="add_cart" sku_id="{{ sku.id }}" id="add_cart">加入购物车</a>
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}  </div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>
            <div class="tab_content" style="display: none;">
				<dl>
                    {% for order_sku in order_skus %}
                        <dt>评论时间:{{ order_sku.update_time }}&nbsp;&nbsp;用户名:{{ order_sku.order.user.username }}</dt>
                        <dd>评论内容:{{ order_sku.comment }}</dd>
                    {% empty %}
                        <dd>暂无商品评论</dd>
                    {% endfor %}
                </dl>
			</div>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ sku.goods.detail|safe }} </dd>
				</dl>
			</div>
		</div>
	</div>
{% endblock main_content %}

{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}

{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
         // 计算商品总价
        function update_sku_amount() {
            // 获取商品的价格
            var price = $('.show_pirze').children('em').text();
            // 获取商品的数量
            var count = $('.num_show').val();
            // 计算商品的价格
            var amount = parseInt(count)*parseFloat(price);
            // 设置商品总价
            $('.total').children('em').text(amount.toFixed(2)+'元');
        }

        // 商品数目的增加
        $('.add').click(function () {
            // 获取商品的数目
            var count = $('.num_show').val();
            // 加1
            count = parseInt(count) + 1;
            // 重新设置
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amount();
        });

        // 商品数目的减少
        $('.minus').click(function () {
            // 获取商品的数目
            var count = $('.num_show').val();
            // 减1
            count = parseInt(count) - 1;
            if (count <= 0) {
                count = 1;
            }
            // 重新设置
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amout();
        });

        // 商品数目手动输入
        $('.num_show').blur(function () {
            // 获取用户输入的商品的数目
            var count = $('.num_show').val();
            // 校验数据
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <= 0){
                count = 1;
            }
            // 重新设置
            // 1.5
            count = parseInt(count);
            $('.num_show').val(count);
            // 更新商品总价
            update_sku_amount();
        })

		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
            // 获取商品id和商品数量
            var sku_id = $(this).attr('sku_id');
            var count = $('.num_show').val();

            // 发起ajax post请求，访问/cart/add, 传递参数: sku_id count
            // 组织参数
            var csrf = $('input[name="csrfmiddlewaretoken"]').val();
            var params = {
                'sku_id': sku_id,
                'count': count,
                'csrfmiddlewaretoken': csrf
            };
            $.post('/cart/add', params, function (data) {
                if (data.res == 5) {
                    // 购物车记录添加成功
{#                    // alert('添加成功')#}
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                           $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车商品的条目数
                                $('#show_count').html(data.cart_count);
                            });

                    });
                }
                else {
                    // 添加失败
                    alert(data.errmsg);
                }
            })
		})
	</script>
{% endblock bottomfiles %}

DailyFresh/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜 - 首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{# 网页主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
        {# 遍历展示商品种类的信息 #}
            {% for category in types %}
			<li><a href="#model0{{ forloop.counter }}" class="{{ category.logo }}">{{ category.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {# 遍历展示首页轮播商品的信息 #}
                {% for banner in index_banner %}
				<li><a href="#"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			{# 遍历显示首页的促销活动信息 #}
            {% for banner in promotion_banner %}
			<a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
		    {% endfor %}
		</div>
	</div>

    {% for category in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">{{ category.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				{# 遍历展示type种类在首页展示的文字商品的信息 #}
                {% for banner in category.title_banner %}
				<a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' category.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ category.image.url }}"></div>
			<ul class="goods_list fl">
				{# 遍历展示type种类在首页展示的图片商品的信息 #}
                {% for banner in category.image_banner %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}




{% endblock body %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>


</body>
</html>

DailyFresh/templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' type.id 1 %}">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
				    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
					{% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {# 遍历显示当前页面上的商品的信息 #}
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous  %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">&lt;上一页</a>
                {% endif %}
                {% for pindex in pages %}
				<a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" {% if pindex == skus_page.number %}class="active"{% endif %}>{{ pindex }}</a>
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页&gt;</a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

DailyFresh/templates/register.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}天天生鲜-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="{% url 'user:register' %}">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>
            <p class="error_tip">{{ errmsg }}</p>
		</div>

	</div>
{% endblock body %}